# Generated by Django 3.0.6 on 2020-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=128)),
                ('is_completed', models.BooleanField(default=False)),
                ('datePublished', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
